/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CuencaShipping {}
}

declare global {


  interface HTMLCuencaShippingElement extends Components.CuencaShipping, HTMLStencilElement {}
  var HTMLCuencaShippingElement: {
    prototype: HTMLCuencaShippingElement;
    new (): HTMLCuencaShippingElement;
  };
  interface HTMLElementTagNameMap {
    'cuenca-shipping': HTMLCuencaShippingElement;
  }
}

declare namespace LocalJSX {
  interface CuencaShipping extends JSXBase.HTMLAttributes<HTMLCuencaShippingElement> {}

  interface IntrinsicElements {
    'cuenca-shipping': CuencaShipping;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


