/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHeader {
    'backButtom': boolean;
    'ionTitle': string;
  }
  interface AppStep1 {
    'backUrl': string;
    'clientId': string;
    'clientName': string;
  }
  interface AppStep2 {
    'backUrl': string;
    'clientId': string;
    'selectedOption': any;
  }
  interface AppStep3 {}
  interface CuencaShipping {
    'apiKey': string;
    'backUrl': string;
    'clientId': string;
    'clientName': string;
  }
  interface SystemAvailable {}
}

declare global {


  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppStep1Element extends Components.AppStep1, HTMLStencilElement {}
  var HTMLAppStep1Element: {
    prototype: HTMLAppStep1Element;
    new (): HTMLAppStep1Element;
  };

  interface HTMLAppStep2Element extends Components.AppStep2, HTMLStencilElement {}
  var HTMLAppStep2Element: {
    prototype: HTMLAppStep2Element;
    new (): HTMLAppStep2Element;
  };

  interface HTMLAppStep3Element extends Components.AppStep3, HTMLStencilElement {}
  var HTMLAppStep3Element: {
    prototype: HTMLAppStep3Element;
    new (): HTMLAppStep3Element;
  };

  interface HTMLCuencaShippingElement extends Components.CuencaShipping, HTMLStencilElement {}
  var HTMLCuencaShippingElement: {
    prototype: HTMLCuencaShippingElement;
    new (): HTMLCuencaShippingElement;
  };

  interface HTMLSystemAvailableElement extends Components.SystemAvailable, HTMLStencilElement {}
  var HTMLSystemAvailableElement: {
    prototype: HTMLSystemAvailableElement;
    new (): HTMLSystemAvailableElement;
  };
  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
    'app-step1': HTMLAppStep1Element;
    'app-step2': HTMLAppStep2Element;
    'app-step3': HTMLAppStep3Element;
    'cuenca-shipping': HTMLCuencaShippingElement;
    'system-available': HTMLSystemAvailableElement;
  }
}

declare namespace LocalJSX {
  interface AppHeader extends JSXBase.HTMLAttributes<HTMLAppHeaderElement> {
    'backButtom'?: boolean;
    'ionTitle'?: string;
  }
  interface AppStep1 extends JSXBase.HTMLAttributes<HTMLAppStep1Element> {
    'backUrl'?: string;
    'clientId'?: string;
    'clientName'?: string;
  }
  interface AppStep2 extends JSXBase.HTMLAttributes<HTMLAppStep2Element> {
    'backUrl'?: string;
    'clientId'?: string;
    'selectedOption'?: any;
  }
  interface AppStep3 extends JSXBase.HTMLAttributes<HTMLAppStep3Element> {}
  interface CuencaShipping extends JSXBase.HTMLAttributes<HTMLCuencaShippingElement> {
    'apiKey'?: string;
    'backUrl'?: string;
    'clientId'?: string;
    'clientName'?: string;
  }
  interface SystemAvailable extends JSXBase.HTMLAttributes<HTMLSystemAvailableElement> {}

  interface IntrinsicElements {
    'app-header': AppHeader;
    'app-step1': AppStep1;
    'app-step2': AppStep2;
    'app-step3': AppStep3;
    'cuenca-shipping': CuencaShipping;
    'system-available': SystemAvailable;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


